- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  debugger: on_failed
  become: true
  tasks:
    - name: install basic tools
      delegate_to: localhost
      package:
        name:
          - vim
          - tmux
          - git
          - telnet
          - colordiff
          - bash-completion
          - tree
          - jq
          - golang
        state: present
      tags:
        - sudo

- hosts: localhost
  gather_facts: false
  any_errors_fatal: true
  debugger: on_failed
  tasks:
    - name: clone vim vundle
      git:
        repo: https://github.com/gmarik/vundle.git
        dest: "{{ ansible_user_dir }}/.vim/bundle/vundle"
        depth: 1
      register: vundle_install

    - name: install vim plugins
      shell: vim +BundleInstall +qall
      when: vundle_install is changed

    - name: configure .vimrc
      copy:
        src: files/vimrc
        dest: "{{ ansible_user_dir }}/.vimrc"
        mode: 0666

    - name: configure .tmux.conf
      copy:
        src: files/tmux-linux.conf
        dest: "{{ ansible_user_dir }}/.tmux.conf"
        mode: 0666

    - name: configure .bashrc
      copy:
        src: files/bashrc
        dest: "{{ ansible_user_dir }}/.bashrc"
        mode: 0666

    - name: configure profile.d
      file:
        path: "{{ ansible_user_dir }}/.profile.d"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: 0755

    - name: configure some alias
      copy:
        src: files/aliases-linux
        dest: "{{ ansible_user_dir }}/.profile.d/bash_aliases.sh"
        mode: 0666

    - name: Configure git
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - { name: "credential.helper", value: "cache --timeout=3600" }
        - { name: "credential.helper", value: "cache --timeout=3600" }
        - { name: "core.editor", value: "/usr/bin/vim" }
        - { name: "user.name", value: "Andy Zhang" }
        - { name: "user.email", value: "azhang@wish.com" }
        - { name: "core.filemode", value: "true" }
        - { name: "color.diff", value: "auto" }
        - { name: "color.status", value: "auto" }
        - { name: "color.branch", value: "auto" }
        - { name: "color.interactive", value: "auto" }
        - { name: "color.ui", value: "true" }
        - { name: "color.pager", value: "true" }
        - { name: "push.followTags", value: "true" }
        - { name: "alias.pr", value: "! git pull -r" }
        - { name: "alias.aa", value: "! git commit -a --amend" }
        - { name: "alias.rs", value: "! git reset --soft" }
        - { name: "alias.c", value: "commit" }
        - { name: "alias.cm", value: "commit -m" }
        - { name: "alias.d", value: "diff" }
        - { name: "alias.s", value: "status --no-renames -v" }
        - { name: "alias.l", value: "log --full-diff" }
